version: '3.8'

services:
  deviceplane:
    build:
      context: .
      dockerfile: dockerfiles/controller-with-db/Dockerfile
    container_name: deviceplane-controller
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=deviceplane
      - DATABASE_PASSWORD=deviceplane
      - DATABASE_NAME=deviceplane
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7.44
    command:
      - --performance_schema=0
      - --sql-mode
      - ""
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=deviceplane
      - MYSQL_PASSWORD=deviceplane
      - MYSQL_DATABASE=deviceplane
    ports:
      - "3306:3306"

